Repository MIT-Emerging-Talent/ET6-foundations-group-01, pull requests merged in 2024-12, with the labels that each got.

#19 Edited Learning Goals for Sukhrob Muborakshoev
  collaboration/learning_goals.md
Labels: documentation

#16 Communication markdown by olumide kolawole
  collaboration/communication.md
Labels: documentation

#24 Adding count_vowels task 1 and test_count_vowels
  .gitignore
  collaboration/guide/0_repository_setup.md
  solutions/count_vowels.py
  solutions/tests/test_count_vowels.py
Labels: enhancement

#15 Edited the template for the communication.md file.
  collaboration/communication.md
Labels: documentation

#29 detailed annotation of constraints
  collaboration/constraints.md
Labels: documentation

#36 communication Dmytro
  collaboration/communication.md
Labels: documentation

#21 My personal learning goals
  collaboration/learning_goals.md
Labels: documentation

#34 Pull Request for Evan Cole's modifications.
  .github/ISSUE_TEMPLATE/help_wanted.md
  .github/ISSUE_TEMPLATE/meeting_agenda.md
  .github/ISSUE_TEMPLATE/new_challenge.md
  .github/ISSUE_TEMPLATE/question.md
  .github/workflows/ci-checks.yml
  .vscode/settings.json
  collaboration/guide/0_repository_setup.md
  solutions/__init__.py
  solutions/tests/__init__.py
Labels: bug, enhancement

#25 Add find_max_in_list function with tests
  solutions/find_max_in_list.py
  solutions/tests/test_find_max_in_list.py
Labels: enhancement

#52 change time in communication
  .vscode/settings.json
  collaboration/communication.md
Labels: documentation

#49 Minor _not final_ changes on the test file, Please check my draft
  solutions/capitalize_character.py
  solutions/tests/test_capitalize_character.py
Labels: enhancement

#46 Dmytro's learning goals
  collaboration/learning_goals.md
Labels: documentation

#53 Communication yuri
  collaboration/communication.md
Labels: documentation
